name: Chuck Norris Issue Assignment Greeting

# Trigger when an issue is assigned
on:
  issues:
    types: [assigned]

jobs:
  chuck-norris-greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Get assignee information
        id: assignee
        run: |
          echo "assignee=${{ github.event.assignee.login }}" >> "$GITHUB_OUTPUT"
          echo "issue_number=${{ github.event.issue.number }}" >> "$GITHUB_OUTPUT"

      - name: Generate Chuck Norris quote with OpenAI
        uses: onmax/oai-createcompletion-githubaction@v1.0
        id: openai-quote
        with:
          model: gpt-3.5-turbo-instruct
          prompt: "Generate a funny Chuck Norris quote related to ${{ steps.assignee.outputs.assignee }} being assigned to work on a GitHub issue. Make it programming/developer themed and motivational. Keep it under 100 words and make it sound like something Chuck Norris would say about conquering code and issues."
          max_tokens: 150
          temperature: 0.8
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}

      - name: Extract and format quote
        id: format-quote
        run: |
          # Extract the quote from OpenAI response
          quote=$(echo '${{ steps.openai-quote.outputs.response }}' | jq -r '.texts[] | sub("\\n"; " ") | sub("\""; "")| sub("\""; "")')
          echo "Extracted quote: $quote"
          # Clean up the quote and format it
          clean_quote=$(echo "$quote" | tr '\n' ' ' | sed 's/^[ \t]*//;s/[ \t]*$//')
          echo "quote=$clean_quote" >> "$GITHUB_OUTPUT"

      - name: Post Chuck Norris greeting comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.assignee.outputs.issue_number }}
          body: |
            🥋 **Chuck Norris says:** 

            > ${{ steps.format-quote.outputs.quote }}

            Good luck @${{ steps.assignee.outputs.assignee }}! 💪 You've got this! 🚀